## main config for gtk-tint

## point to the directory where all GTK themes are kept
theme_dir = '$HOME/.themes/'

## point to the theme to use as a base
## this is defined explicitly here to prevent tinting an already tintied theme.
base_theme = ''

## this option defines how to get a base theme for a specific system. it pulls from the inputs/base-theme directory for a script with a matching name.
base_theme_module = 'gtk2.sh'

## define tint factor to use. gtk-tint uses this value if the input script doesn't provide a tint factor AND if the fine-grained rules don't override the tint factor for a specific element.
fallback_tint_factor = 0.2

## specify the module to use to get the accent color (path)
accent_module = "kde_accent/"

## define which tinting method to use
tint_method = "oklab-linear-interpolation"

## define the suffix to tint the base theme with
alter_suffix = "-tint"

## specify a list of output modules to call.
## these are directories containing a script, a config for that script, and other supporting files.
outputs = [ 'gtk2/', 'gtk3/', 'gtk4/' ]
