*** NOTICE
Because the applicability of the project has increased, I have decided to rename it to reflect this. The repository will still be here, but I may move it in the future. I will handle making sure that people coming to this page know where to find the new repo when it goes up.

* UniCATE (Previously GTK-Tint)
UniCATE (Unify Colors Across Theme Engines) is a program designed to dynamically update various elements of your linux environment to allow for a more unified look.

** Dependencies:
Note that modules may have their own dependencies (example: the kde-accent module assumes you have `kreadconfig5` installed on your system), so this section will only list dependencies of the base tool. When making your own modules, be sure to include those dependencies in some kind of build file, or at least a readme.
*** Python:
- CherryPicker

** Status

[!NOTE] This project is still under active development.

** Repository Structure

*** main-conf.toml

This file, `main-conf.toml`, serves as the configuration file. It allows you to specify which theme to tint, how to tint it, and which colors to use for tinting.

*** unicate.sh

The `unicate.sh` script is responsible for organizing the modules and providing a consistent framework through which to utilize them.

*** toml-parse.py

This script handles the toml parsing, because I couldn't find a good rust or bash implementation. It also converts the toml data into a form that the main script can use, namely an associated array where the keys are concatenations of the subtable values.

*** inputs/

The `inputs/` directory contains various scripts that determine how the accent colors are selected. If you want to integrate this tool with another program or extend gtk-tint's functionality, you can typically add a file in this directory.

There are two subdirectories within the `inputs/` directory: `accent` and `base-theme`. All input modules fall into one of those two categories. More info on them can be found in the modules page of the docs.

*** outputs/
The `outputs/` directory contains several directories (herein referred to as "output modules"). Each output module contains a script to execute to alter different aspects of the theme it targets, and a `.toml` file defining module-specific configurations. If you want gtk-tint to also apply to other aspects of your system, this is where you'd put code that does so.

*** tint-methods/
This directory contains the compiled binaries used to tint the colors. adding your own compiled scripts is also possible.

** MODULES
A module is a collection of scripts that can be run by UniCATE to either read or write relevant data. Each module gets its own subdirectory, and contains an `invoke.sh` file. More information on modules can be found in the documentation section by the same name.
